### ISSUE TITLE
Maze size adaptation 

### ISSUE THREAD

**Issue by RomarioKavin1** [micromouseonline/mazerunner-core#4]
How can I run this code on a 25x25 maze with the centre as a 3x3 block

**Comment by RomarioKavin1** [comment]
Need the solution a bit urgently

**Comment by micromouseonline** [comment]
This is experminetal code, not intended for production. It is subject to large changes without warning.

In any case, the Arduino processor is not going to have enough memory to store and flod a maze bigger than 16x16 using the techniques here.

**Comment by micromouseonline** [comment]
Not really. There is not enough RAM on the processor. Using the methods already there, you would need 576 bytes for the maze and 1152 bytes for the flooding data.

**Comment by RahulRST** [comment]
Ohh okay thank you.Appreciate your help
But i tried increasing the maze size to 22x22 which works perfectly. I think the RAM is just sufficient for this size of the maze.

**Comment by micromouseonline** [comment]
It may well appear to work at some larger sizes but there are two potentially big problems. One is that the cost array used to create a route only holds 8 bit values. When there are more than 256 cells in the maze data, the cost values might overflow and give unpredictable results.

Anothe possible problem is that larger strucures for the maze might well fit in RAM but there will be less memory available for the function stack. This can produce vey hard to find errors where things may appear to work until some particular set of circumstances reveals an error and the robot mysteriously stops working. Code mey appear to work fine until you make some other change that just overflows the stack slightly.

All these can be overcome by re-writing the maze.h code to use less space but that would not be something I would do.

**Comment by RahulRST** [comment]
Ohh okay thank you. Appreciate your help. I'll look into it
